## Code Structure in folder scr/

Model.R
    'default.model' regression on pm2.5 values
        works for sinple or multiple lags, 
        w/ or w/o mobility data 
    'two.bands.model' regression on 1) pm2.5 baseline and 2) wildfire contribution
        works for sinple or multiple lags, 
        w/ or w/o mobility data  single
    || above functions are validated for single-lag scenario only  
  
ExeSingleLagModel.R 
    run default.model for single lag w/o mobility (varies degree of freedom setup)

ExeDistLagModel.R 
    run default.model for multiple lags w/o mobility (varies degree of freedom setup)

ExeTwoBandSingleLagModel.R 
    run two.bands.model for single lag w/o mobility (varies degree of freedom setup)

ExeTwoBandDistLagModel.R 
    run two.bands.model for multiple lags w/o mobility (varies degree of freedom setup)

Utilities.R
    'load.data'           load data
    'split.pm'            split pm2.5 into baseline and wildfire contribution
    'create.lag'          create lags for pm2.5 or baseline or wildfire contribution
    'create.output.name'  create modelling output file names
    'trans.coef'          transform coefficients in Poisson model 
        Please transform before saving as csv!
        percent of change given 10ug/m3 increases in pm values
        (how to interpret distributed lag model????????)

Visualization script name ....
    read csv1 csv2 
    plot plot plot 
    a lot of formatting here 
    save as pdf ... 

## Modelling output file names
  ## 
  OneBand     singleLag21      wMobility
  OneBand     singleLag21      woMobility
  ## ?????????????????????????????? ???????????? df????????
  TwoBand     MultiLag0       wMobility
  ... 
  TwoBand     MultiLag21       wMobility
  ##
  TwoBand     MultiLag0        woMobility
  ... 
  TwoBand     MultiLag21       woMobility
  
  output table 
  df.date df.tmmx df.rmax mobility lag variable coef coef.low coef.high
  ?????? df.combo
  save without column name!!!!
  
  
## Visualization output file names ....


## Tests.R


## some exploration and visualization 
    combine.R (clean data!!!)
    GoogleMobility.R
    HazardSmokeSystem.R
    SummarizeData.R
    calfire.R
    Exploratory...
    (total)TestCount.R
    
## Data Description 

# https://developers.google.com/earth-engine/datasets/catalog/IDAHO_EPSCOR_TERRACLIMATE#bands
# https://developers.google.com/earth-engine/datasets/catalog/IDAHO_EPSCOR_GRIDMET?hl=es#bands
Name	Units	Min	  Max	    Description
pr	  mm	  0*	  7245*   Precipitation accumulation
srad	W/m^2 0*	  5477*	  Downward surface shortwave radiation
tmmx	K	    -670*	576*	  Maximum temperature
rmax	%	    1.05*	100*    Maximum relative humidity
sph	  kg/kg	0*	  0.02*   Specific humidity

Name	      Units	    Min	  Max	    Description
cases       people                  Confirmed COVID cases            
deaths      people                  Deaths of COVID
population  people
pm25        ug/m^3